/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eydfeyiiukllshokcgrh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZGZleWlpdWtsbHNob2tjZ3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4OTc1NjcsImV4cCI6MjA4OTQ3MzU2N30.ebbG-T89rmKOKlv25xz__H3n5sHVPwK8Sqx8j-2szVU"